backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "_assets/images"
public_folder: "_site/assets"
collections:
  - name: "ideas" # Used in routes, e.g., /admin/collections/blog
    label: "Ideas" # Used in the UI
    folder: "_posts/ideas" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "idea"}
      - {label: "Title (Idea Name)", name: "title", widget: "string"}
      - {label: "Wistia Video ID", name: "wistia_video_id", widget: "string"}
